export const MAP_ASPECT_RATIO = 1.22
export const RENDER_SCALE = 12
export const PHYSICS_SCALE = 1
export const PHYSICS_TO_RENDER_SCALE = RENDER_SCALE / PHYSICS_SCALE
export const RENDER_TO_PHYSICS_SCALE = PHYSICS_SCALE / RENDER_SCALE
